Remove unused GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2 from datanode compose
Graylog2/docker-compose pull request #78
Opened 2024-10-17 10:15 UTC by todvora

Merge only after updating to 6.1! Related to https://github.com/Graylog2/graylog-docker/pull/278

## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

2024-10-24 06:39 UTC, bernd approved these changes

2024-10-29 11:05 UTC, bernd requested changes
@todvora The variable is used in more files.

2024-10-30 12:29 UTC, todvora commented
@bernd sorry, I focused only on the open part. Fixed now.

2024-10-30 16:57 UTC, bernd requested changes

2024-10-30 16:57 UTC, bernd commented on open-core/docker-compose.yml
> +  elasticsearch:
I think this was added by accident?

2024-10-30 16:58 UTC, bernd requested changes

2024-10-30 16:58 UTC, bernd commented on open-core/docker-compose.yml
> +      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
Same as above.

2024-10-30 16:58 UTC, bernd commented on open-core/docker-compose.yml
> +  elasticsearch:
Same as above.

2024-11-04 18:24 UTC, bernd approved these changes
Thanks!

2025-02-17 08:52 UTC, merged